Starter branch edge to edge implementation
google-developer-training/basic-android-kotlin-compose-training-dessert-release pull request #11
Opened 2023-08-03 00:33 UTC by the-scrambler

Merge pending codelab update.

2023-08-08 22:48 UTC, android-dev-lxl approved these changes

2023-08-14 07:48 UTC, johnshea requested changes
Navigation bar is not translucent on API 33 but it should be.

See [PR for branch `main-e2e`](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dessert-release/pull/12) for screenshot and additional changes needed.

2023-08-14 07:48 UTC, johnshea commented on app/src/main/java/com/example/dessertrelease/ui/DessertReleaseScreen.kt
> +@Composable
Unless there is a reason for moving the function here, move the function back to its original location in the file so the diff is smaller and only for the changes in the function body.

2023-08-18 17:19 UTC, johnshea approved these changes
LGTM but upgrade gradle wrapper to `8.2`

2023-09-15 01:07 UTC, android-dev-lxl commented
Gradle update was needed

2023-09-18 19:14 UTC, johnshea approved these changes
lgtm

2023-09-20 19:27 UTC, merged