Main branch edge to edge implementation
google-developer-training/basic-android-kotlin-compose-training-dessert-release pull request #12
Opened 2023-08-03 00:34 UTC by the-scrambler

Merge pending codelab update.

2023-08-03 20:40 UTC, android-dev-lxl commented
Please remove this from the gradle file and include as needed. 

       ` freeCompilerArgs += "-opt-in=androidx.compose.material3.ExperimentalMaterial3Api"`

2023-08-03 20:51 UTC, android-dev-lxl requested changes
Inner padding is not set correctly. 


Before
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dessert-release/assets/24260141/4b4584bb-3d14-4345-ae1c-5faadff8ad96)

With Edge to Edge:
![image](https://github.com/google-developer-training/basic-android-kotlin-compose-training-dessert-release/assets/24260141/474d97c9-5705-4df1-9666-cc8d4b89afee)

2023-08-03 20:51 UTC, android-dev-lxl commented on app/src/main/java/com/example/dessertrelease/ui/DessertReleaseScreen.kt
>  }
You should always set the inner padding to the content padding for lists. Please do the same for Grid layout also.
 ```
            modifier = Modifier
                    .padding(
                        vertical = dimensionResource(R.dimen.padding_medium),
                        horizontal = dimensionResource(R.dimen.padding_medium)
                    )
                    .fillMaxWidth(),
                contentPadding = innerPadding
            )
```

2023-08-03 20:51 UTC, android-dev-lxl commented on app/src/main/java/com/example/dessertrelease/ui/DessertReleaseScreen.kt
> +            end = dimensionResource(R.dimen.padding_medium)
If you set the required padding to the modifier you can just set scaffold padding to the content padding.
`contentPadding = contentPadding,`

2023-08-08 22:46 UTC, android-dev-lxl approved these changes

2023-08-14 07:40 UTC, johnshea requested changes
Navigation bar on API 33 is not translucent but should be.

Upgrade gradle wrapper to `8.2`
Upgrade Compose compiler to `1.5.1`
Upgrade BOM to `2023.08.00`
Project `build.gradle.kts` - upgrade `plugin` versions to the lastest. (Current latest is `1.8.0` and `1.9.0`)

<img width="303" alt="Screenshot 2023-08-14 at 10 33 39 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-dessert-release/assets/7107817/52137d52-edc1-4ff1-9129-84432db25dfc">

2023-08-16 23:30 UTC, johnshea requested changes
Nav bar is not translucent but it should be.

<img width="262" alt="Screenshot 2023-08-17 at 2 29 47 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-dessert-release/assets/7107817/3884a7e2-6a0d-449b-abe7-4c0c16c0c1ec">

2023-08-21 15:37 UTC, johnshea requested changes
API 33 GridLayout - navigation bar is not translucent but it should be.

<img width="475" alt="Screenshot 2023-08-21 at 11 30 30 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-dessert-release/assets/7107817/bb516f78-6ac7-417a-bdd9-d1303b530371">

2023-09-13 05:02 UTC, android-dev-lxl approved these changes

2023-09-14 17:31 UTC, johnshea approved these changes
lgtm with 2 nits.

2023-09-20 19:27 UTC, merged